### ISSUE TITLE
onboarding 

### ISSUE THREAD

**Issue by EggiEl** [OberhauserJulia/Team-Globus#14]
Welcome to Reflectale!
Embark on an interactive journey that reveals the lifecycle of your product. Enter the room with your headphones on as you listen to the story of your product's production journey. You'll be guided through each stage it went through until it arrived here in this installation, helping you gain a deeper appreciation for the value of its components.

**Comment by PetzInfo** [comment]
Onboarding mit EN-Default, 0,9 und "....." implementiert
